### ISSUE TITLE
LoLo_network_test#1

### ISSUE THREAD

**Issue by georgis8581** [georgis8581/Dissertation#1]
@nilsgoldbeck I uploaded 'LoLo_network_test.py' in code section and the last line doesn't work. Is it because of capacities that have not yet been defined? Thank you.

**Comment by nilsgoldbeck** [comment]
The error message I get tells me that there is a type error. Seems like you are assigning a list instead of a scalar to each node as demand parameter.

In the first instance, it would probably be better to create the graph exactly with the same commands as in the [example in the docs](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.flow.min_cost_flow.html).
